[phases.setup]
nixPkgs = ["nodejs", "python310", "python310Packages.pip", "gcc", "libffi", "openssl"]

[phases.install]
cmds = [
  "npm install",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r backend/requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
